### ISSUE TITLE
null does not work as left or right props

### ISSUE THREAD

**Issue by codrin-iftimie** [iampava/react-sliding-item#1]
Usually, devs will return null or undefined
https://github.com/iampava/react-sliding-item/blob/main/src/index.tsx#L60C3-L60C28
I'd check for `!left` instead

**Comment by iampava** [comment]
I'm afraid I don't agree. The prop is optional so if you put something other than `undefined` I will consider you want it rendered.

The only check that makes sense IMO is with `undefined` :)
